# Generated by Django 2.2 on 2019-04-07 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monhoc', '0003_delete_diemso'),
        ('giangday', '0003_delete_lichgiangday'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiaoVien',
        ),
    ]
