# Generated by Django 2.2 on 2019-04-07 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danhmuc', '0002_auto_20190407_0355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trinhdo', models.CharField(blank=True, choices=[('DH', 'Cử nhân'), ('THS', 'Thạc sĩ'), ('TS', 'Tiến sĩ'), ('GS', 'Giáo sư')], default='DH', max_length=255, null=True, verbose_name='Trình độ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name_plural': 'Giao viên',
            },
        ),
        migrations.CreateModel(
            name='LichGiangDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigian', models.DateTimeField(verbose_name='Thời gian')),
                ('giaovien', models.ForeignKey(default=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='giaovien.GiaoVien', verbose_name='Giáo viên')),
                ('monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danhmuc.MonHoc', verbose_name='Môn dạy')),
            ],
            options={
                'verbose_name_plural': 'Lịch giảng dạy',
            },
        ),
    ]
