# Generated by Django 2.2 on 2019-04-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenDanhMuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendanhmuc', models.CharField(blank=True, max_length=255, null=True)),
                ('mota', models.CharField(blank=True, max_length=255, null=True)),
                ('kieudanhmuc', models.IntegerField(default=0)),
            ],
        ),
    ]
