# Generated by Django 2.2 on 2019-04-07 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danhmuc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoiHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoi_hoc', models.CharField(default='', max_length=255, verbose_name='Tên khối học')),
            ],
            options={
                'verbose_name_plural': 'Khối học',
            },
        ),
        migrations.CreateModel(
            name='KyHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ky_hoc', models.CharField(default='', max_length=255, verbose_name='Tên kỳ học')),
            ],
            options={
                'verbose_name_plural': 'Kỳ học',
            },
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop_hoc', models.CharField(default='', max_length=255, verbose_name='Tên lớp học')),
                ('khoi_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danhmuc.KhoiHoc', verbose_name='Khối học')),
            ],
            options={
                'verbose_name_plural': 'Lớp học',
            },
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon_hoc', models.CharField(default='', max_length=255, verbose_name='Tên môn học')),
                ('so_tiet', models.IntegerField(default=0, verbose_name='Số tiết học')),
            ],
            options={
                'verbose_name_plural': 'Môn học',
            },
        ),
        migrations.DeleteModel(
            name='TenDanhMuc',
        ),
    ]
